source 'https://rubygems.org'

gem 'rails', '~> 5.0.1'
gem 'pg', '~> 0.18'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'jquery-rails'
gem 'turbolinks'
gem 'devise'
gem 'kaminari'
gem 'foundation-rails'

group :development, :test do
  gem 'pry-rails'
  gem 'rspec-rails', '~> 3.5'
  gem 'capybara'
  gem 'factory_bot'
  gem 'launchy'
  gem 'faker'
end

group :development do
  gem 'web-console'
  gem 'spring'
end
